# action.yml
name: 'Flix Test'
description: 'Perform Flix unit tests and benchmark tests'
inputs:
  flix-version:
    description: 'Version of Flix to use'
    required: true
  test-dir:
    description: 'Directory containing Flix test files.'
    required: true
    default: './test/'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.flix-version }}
    - ${{ inputs.test-dir }}

