# action.yml
name: 'Flix Test'
description: 'Perform Flix unit tests and benchmark tests'
inputs:
  version-type:
    description: 'The type of version to use: nightly or release'
    required: true
    default: release
  release-tag:
    description: 'The tag of the release to use: vX.X.X'
  nightly-date:
    description: 'The date of the nightly build to use: YYYY-MM-DD'
runs:
  using: 'node12'
  main: 'index.js'

